//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Nova/Settings/InputMapping.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMapping: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMapping()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMapping"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""65ac26fd-cd8d-45ae-a7d9-3c5ae38672aa"",
            ""actions"": [
                {
                    ""name"": ""StepForward"",
                    ""type"": ""Button"",
                    ""id"": ""97518737-f6e5-4e52-b2f7-e53d1d2fc506"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Auto"",
                    ""type"": ""Button"",
                    ""id"": ""92a46dc0-453a-4666-9de8-883c06876c65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""85569b9c-0c57-4872-8a36-f99714b4e4fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Load"",
                    ""type"": ""Button"",
                    ""id"": ""a92328a6-5459-4764-be99-02e914f88d25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSave"",
                    ""type"": ""Button"",
                    ""id"": ""627177ba-de96-4285-a826-a5df6e6815fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickLoad"",
                    ""type"": ""Button"",
                    ""id"": ""c9c9db54-8ca8-49ab-b089-2ce20add2fcf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""9c2946bf-47fe-46f6-ab70-58e3b18b337c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowLog"",
                    ""type"": ""Button"",
                    ""id"": ""544b3e00-c037-40d4-803e-3494c1bec7f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowConfig"",
                    ""type"": ""Button"",
                    ""id"": ""ec8814f7-fe10-4ff6-974d-7c9b1bf05f80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReturnTitle"",
                    ""type"": ""Button"",
                    ""id"": ""c66b99b6-59d8-4203-ac1b-5ca9140e2942"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EditorReloadScripts"",
                    ""type"": ""Button"",
                    ""id"": ""57a915be-4fe8-4ce0-a5b1-30432e1fed4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5362a006-d294-4d89-827b-d789d73a8b9c"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StepForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5acc9ceb-9d7e-48a6-b9ce-24b7cc14cb43"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StepForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""420ecd55-0df9-4d09-85d0-8b22e2bf0548"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StepForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f404172-ba2b-436d-9d5c-01d98f682bba"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StepForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d4dd35d-73de-4818-84c5-76fee75e842c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad scheme"",
                    ""action"": ""StepForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""feade573-fff2-41dd-bd5c-bb46cfc47039"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Auto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eedfc028-1de5-46e2-9ebb-5a0ebe303fcb"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Auto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2f14355-a8c3-4cf1-ab58-418da3df5f21"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f9d881f-a173-41ee-971e-d71410cf0225"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Load"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36c4d00d-fb1a-4cbe-8f77-fc78b65a8232"",
                    ""path"": ""<Keyboard>/f9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSave"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2baaa573-4c7b-47dd-b63b-5272886c712f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSave"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09b717e5-ac69-44c7-aabd-7e9281d379e6"",
                    ""path"": ""<Keyboard>/f10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickLoad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""729b98f7-63c0-47c4-b0d1-815ac720c9ce"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickLoad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c3de28e-b588-42e0-8d28-a985558f3268"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea5e4dda-97b4-43d8-b433-aa4a3eab5bc5"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowLog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04c50cbd-6219-40fb-88fc-58c51d75ca12"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowLog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d2314ed-fa62-4b96-8fd1-f0c8445dd1f5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EditorReloadScripts"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92bf9db5-1b27-40b7-9488-2c562e0888b8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReturnTitle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8fc7ffa-8c74-450a-aee7-8a5b1589d708"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReturnTitle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c479d84e-2332-4a57-a18c-92a66f77fe7e"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowConfig"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09acf0ef-9272-4db1-9525-12b158d959da"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowConfig"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GameHold"",
            ""id"": ""acfde6a6-59ea-4ffb-831c-700c4aa3b5e1"",
            ""actions"": [
                {
                    ""name"": ""QuitGame"",
                    ""type"": ""Button"",
                    ""id"": ""86e11927-ae0f-4119-9fcf-b4a7f85785be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""286710f5-7f7a-4e67-9c7e-f8f1445d2060"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuitGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2b3e6ff-768c-44be-b863-a0712f5118fb"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuitGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GamePress"",
            ""id"": ""98122892-a6f4-4864-847c-cf8f1c4df8a4"",
            ""actions"": [
                {
                    ""name"": ""FastForward"",
                    ""type"": ""Button"",
                    ""id"": ""304a877d-49ab-4190-a7fc-14fcf02aa8ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c8ace76c-8af3-4f56-b44c-90edc44d64dc"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""120e7ba0-8729-4597-b656-3f2a0655d02a"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""4e08a8e8-86e4-410b-9f73-bfad090db1b9"",
            ""actions"": [
                {
                    ""name"": ""LeaveView"",
                    ""type"": ""Button"",
                    ""id"": ""619a9afb-57ff-40d0-bdd2-e72d1959274e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EditorUnlock"",
                    ""type"": ""Button"",
                    ""id"": ""d67d6497-da0c-4e11-996f-a4d56a93c03b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4793c7e1-6f36-4028-9194-7eca7a7265c5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeaveView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1d10463-e671-481d-a505-e280887e85e0"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeaveView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3560323-1151-4dae-bc18-888f0945785b"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EditorUnlock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Always"",
            ""id"": ""15432f44-28e6-4444-98f2-02660e8764e3"",
            ""actions"": [
                {
                    ""name"": ""ToggleFullScreen"",
                    ""type"": ""Button"",
                    ""id"": ""55d742f2-1c5d-40e5-8984-6be8a8a681c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchLanguage"",
                    ""type"": ""Button"",
                    ""id"": ""e9a9be43-64eb-4bf4-b12e-4bfd01a50253"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d125ba94-d955-47b1-9b3f-b3b88108beb5"",
                    ""path"": ""<Keyboard>/f11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleFullScreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b7dc04c-d3fd-4df1-9727-59681c32d94a"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchLanguage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad scheme"",
            ""bindingGroup"": ""Gamepad scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_StepForward = m_Game.FindAction("StepForward", throwIfNotFound: true);
        m_Game_Auto = m_Game.FindAction("Auto", throwIfNotFound: true);
        m_Game_Save = m_Game.FindAction("Save", throwIfNotFound: true);
        m_Game_Load = m_Game.FindAction("Load", throwIfNotFound: true);
        m_Game_QuickSave = m_Game.FindAction("QuickSave", throwIfNotFound: true);
        m_Game_QuickLoad = m_Game.FindAction("QuickLoad", throwIfNotFound: true);
        m_Game_ToggleDialogue = m_Game.FindAction("ToggleDialogue", throwIfNotFound: true);
        m_Game_ShowLog = m_Game.FindAction("ShowLog", throwIfNotFound: true);
        m_Game_ShowConfig = m_Game.FindAction("ShowConfig", throwIfNotFound: true);
        m_Game_ReturnTitle = m_Game.FindAction("ReturnTitle", throwIfNotFound: true);
        m_Game_EditorReloadScripts = m_Game.FindAction("EditorReloadScripts", throwIfNotFound: true);
        // GameHold
        m_GameHold = asset.FindActionMap("GameHold", throwIfNotFound: true);
        m_GameHold_QuitGame = m_GameHold.FindAction("QuitGame", throwIfNotFound: true);
        // GamePress
        m_GamePress = asset.FindActionMap("GamePress", throwIfNotFound: true);
        m_GamePress_FastForward = m_GamePress.FindAction("FastForward", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_LeaveView = m_UI.FindAction("LeaveView", throwIfNotFound: true);
        m_UI_EditorUnlock = m_UI.FindAction("EditorUnlock", throwIfNotFound: true);
        // Always
        m_Always = asset.FindActionMap("Always", throwIfNotFound: true);
        m_Always_ToggleFullScreen = m_Always.FindAction("ToggleFullScreen", throwIfNotFound: true);
        m_Always_SwitchLanguage = m_Always.FindAction("SwitchLanguage", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private List<IGameActions> m_GameActionsCallbackInterfaces = new List<IGameActions>();
    private readonly InputAction m_Game_StepForward;
    private readonly InputAction m_Game_Auto;
    private readonly InputAction m_Game_Save;
    private readonly InputAction m_Game_Load;
    private readonly InputAction m_Game_QuickSave;
    private readonly InputAction m_Game_QuickLoad;
    private readonly InputAction m_Game_ToggleDialogue;
    private readonly InputAction m_Game_ShowLog;
    private readonly InputAction m_Game_ShowConfig;
    private readonly InputAction m_Game_ReturnTitle;
    private readonly InputAction m_Game_EditorReloadScripts;
    public struct GameActions
    {
        private @InputMapping m_Wrapper;
        public GameActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @StepForward => m_Wrapper.m_Game_StepForward;
        public InputAction @Auto => m_Wrapper.m_Game_Auto;
        public InputAction @Save => m_Wrapper.m_Game_Save;
        public InputAction @Load => m_Wrapper.m_Game_Load;
        public InputAction @QuickSave => m_Wrapper.m_Game_QuickSave;
        public InputAction @QuickLoad => m_Wrapper.m_Game_QuickLoad;
        public InputAction @ToggleDialogue => m_Wrapper.m_Game_ToggleDialogue;
        public InputAction @ShowLog => m_Wrapper.m_Game_ShowLog;
        public InputAction @ShowConfig => m_Wrapper.m_Game_ShowConfig;
        public InputAction @ReturnTitle => m_Wrapper.m_Game_ReturnTitle;
        public InputAction @EditorReloadScripts => m_Wrapper.m_Game_EditorReloadScripts;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void AddCallbacks(IGameActions instance)
        {
            if (instance == null || m_Wrapper.m_GameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameActionsCallbackInterfaces.Add(instance);
            @StepForward.started += instance.OnStepForward;
            @StepForward.performed += instance.OnStepForward;
            @StepForward.canceled += instance.OnStepForward;
            @Auto.started += instance.OnAuto;
            @Auto.performed += instance.OnAuto;
            @Auto.canceled += instance.OnAuto;
            @Save.started += instance.OnSave;
            @Save.performed += instance.OnSave;
            @Save.canceled += instance.OnSave;
            @Load.started += instance.OnLoad;
            @Load.performed += instance.OnLoad;
            @Load.canceled += instance.OnLoad;
            @QuickSave.started += instance.OnQuickSave;
            @QuickSave.performed += instance.OnQuickSave;
            @QuickSave.canceled += instance.OnQuickSave;
            @QuickLoad.started += instance.OnQuickLoad;
            @QuickLoad.performed += instance.OnQuickLoad;
            @QuickLoad.canceled += instance.OnQuickLoad;
            @ToggleDialogue.started += instance.OnToggleDialogue;
            @ToggleDialogue.performed += instance.OnToggleDialogue;
            @ToggleDialogue.canceled += instance.OnToggleDialogue;
            @ShowLog.started += instance.OnShowLog;
            @ShowLog.performed += instance.OnShowLog;
            @ShowLog.canceled += instance.OnShowLog;
            @ShowConfig.started += instance.OnShowConfig;
            @ShowConfig.performed += instance.OnShowConfig;
            @ShowConfig.canceled += instance.OnShowConfig;
            @ReturnTitle.started += instance.OnReturnTitle;
            @ReturnTitle.performed += instance.OnReturnTitle;
            @ReturnTitle.canceled += instance.OnReturnTitle;
            @EditorReloadScripts.started += instance.OnEditorReloadScripts;
            @EditorReloadScripts.performed += instance.OnEditorReloadScripts;
            @EditorReloadScripts.canceled += instance.OnEditorReloadScripts;
        }

        private void UnregisterCallbacks(IGameActions instance)
        {
            @StepForward.started -= instance.OnStepForward;
            @StepForward.performed -= instance.OnStepForward;
            @StepForward.canceled -= instance.OnStepForward;
            @Auto.started -= instance.OnAuto;
            @Auto.performed -= instance.OnAuto;
            @Auto.canceled -= instance.OnAuto;
            @Save.started -= instance.OnSave;
            @Save.performed -= instance.OnSave;
            @Save.canceled -= instance.OnSave;
            @Load.started -= instance.OnLoad;
            @Load.performed -= instance.OnLoad;
            @Load.canceled -= instance.OnLoad;
            @QuickSave.started -= instance.OnQuickSave;
            @QuickSave.performed -= instance.OnQuickSave;
            @QuickSave.canceled -= instance.OnQuickSave;
            @QuickLoad.started -= instance.OnQuickLoad;
            @QuickLoad.performed -= instance.OnQuickLoad;
            @QuickLoad.canceled -= instance.OnQuickLoad;
            @ToggleDialogue.started -= instance.OnToggleDialogue;
            @ToggleDialogue.performed -= instance.OnToggleDialogue;
            @ToggleDialogue.canceled -= instance.OnToggleDialogue;
            @ShowLog.started -= instance.OnShowLog;
            @ShowLog.performed -= instance.OnShowLog;
            @ShowLog.canceled -= instance.OnShowLog;
            @ShowConfig.started -= instance.OnShowConfig;
            @ShowConfig.performed -= instance.OnShowConfig;
            @ShowConfig.canceled -= instance.OnShowConfig;
            @ReturnTitle.started -= instance.OnReturnTitle;
            @ReturnTitle.performed -= instance.OnReturnTitle;
            @ReturnTitle.canceled -= instance.OnReturnTitle;
            @EditorReloadScripts.started -= instance.OnEditorReloadScripts;
            @EditorReloadScripts.performed -= instance.OnEditorReloadScripts;
            @EditorReloadScripts.canceled -= instance.OnEditorReloadScripts;
        }

        public void RemoveCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameActions instance)
        {
            foreach (var item in m_Wrapper.m_GameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameActions @Game => new GameActions(this);

    // GameHold
    private readonly InputActionMap m_GameHold;
    private List<IGameHoldActions> m_GameHoldActionsCallbackInterfaces = new List<IGameHoldActions>();
    private readonly InputAction m_GameHold_QuitGame;
    public struct GameHoldActions
    {
        private @InputMapping m_Wrapper;
        public GameHoldActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @QuitGame => m_Wrapper.m_GameHold_QuitGame;
        public InputActionMap Get() { return m_Wrapper.m_GameHold; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameHoldActions set) { return set.Get(); }
        public void AddCallbacks(IGameHoldActions instance)
        {
            if (instance == null || m_Wrapper.m_GameHoldActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameHoldActionsCallbackInterfaces.Add(instance);
            @QuitGame.started += instance.OnQuitGame;
            @QuitGame.performed += instance.OnQuitGame;
            @QuitGame.canceled += instance.OnQuitGame;
        }

        private void UnregisterCallbacks(IGameHoldActions instance)
        {
            @QuitGame.started -= instance.OnQuitGame;
            @QuitGame.performed -= instance.OnQuitGame;
            @QuitGame.canceled -= instance.OnQuitGame;
        }

        public void RemoveCallbacks(IGameHoldActions instance)
        {
            if (m_Wrapper.m_GameHoldActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameHoldActions instance)
        {
            foreach (var item in m_Wrapper.m_GameHoldActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameHoldActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameHoldActions @GameHold => new GameHoldActions(this);

    // GamePress
    private readonly InputActionMap m_GamePress;
    private List<IGamePressActions> m_GamePressActionsCallbackInterfaces = new List<IGamePressActions>();
    private readonly InputAction m_GamePress_FastForward;
    public struct GamePressActions
    {
        private @InputMapping m_Wrapper;
        public GamePressActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @FastForward => m_Wrapper.m_GamePress_FastForward;
        public InputActionMap Get() { return m_Wrapper.m_GamePress; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePressActions set) { return set.Get(); }
        public void AddCallbacks(IGamePressActions instance)
        {
            if (instance == null || m_Wrapper.m_GamePressActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamePressActionsCallbackInterfaces.Add(instance);
            @FastForward.started += instance.OnFastForward;
            @FastForward.performed += instance.OnFastForward;
            @FastForward.canceled += instance.OnFastForward;
        }

        private void UnregisterCallbacks(IGamePressActions instance)
        {
            @FastForward.started -= instance.OnFastForward;
            @FastForward.performed -= instance.OnFastForward;
            @FastForward.canceled -= instance.OnFastForward;
        }

        public void RemoveCallbacks(IGamePressActions instance)
        {
            if (m_Wrapper.m_GamePressActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamePressActions instance)
        {
            foreach (var item in m_Wrapper.m_GamePressActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamePressActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamePressActions @GamePress => new GamePressActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_LeaveView;
    private readonly InputAction m_UI_EditorUnlock;
    public struct UIActions
    {
        private @InputMapping m_Wrapper;
        public UIActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeaveView => m_Wrapper.m_UI_LeaveView;
        public InputAction @EditorUnlock => m_Wrapper.m_UI_EditorUnlock;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @LeaveView.started += instance.OnLeaveView;
            @LeaveView.performed += instance.OnLeaveView;
            @LeaveView.canceled += instance.OnLeaveView;
            @EditorUnlock.started += instance.OnEditorUnlock;
            @EditorUnlock.performed += instance.OnEditorUnlock;
            @EditorUnlock.canceled += instance.OnEditorUnlock;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @LeaveView.started -= instance.OnLeaveView;
            @LeaveView.performed -= instance.OnLeaveView;
            @LeaveView.canceled -= instance.OnLeaveView;
            @EditorUnlock.started -= instance.OnEditorUnlock;
            @EditorUnlock.performed -= instance.OnEditorUnlock;
            @EditorUnlock.canceled -= instance.OnEditorUnlock;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // Always
    private readonly InputActionMap m_Always;
    private List<IAlwaysActions> m_AlwaysActionsCallbackInterfaces = new List<IAlwaysActions>();
    private readonly InputAction m_Always_ToggleFullScreen;
    private readonly InputAction m_Always_SwitchLanguage;
    public struct AlwaysActions
    {
        private @InputMapping m_Wrapper;
        public AlwaysActions(@InputMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleFullScreen => m_Wrapper.m_Always_ToggleFullScreen;
        public InputAction @SwitchLanguage => m_Wrapper.m_Always_SwitchLanguage;
        public InputActionMap Get() { return m_Wrapper.m_Always; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AlwaysActions set) { return set.Get(); }
        public void AddCallbacks(IAlwaysActions instance)
        {
            if (instance == null || m_Wrapper.m_AlwaysActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AlwaysActionsCallbackInterfaces.Add(instance);
            @ToggleFullScreen.started += instance.OnToggleFullScreen;
            @ToggleFullScreen.performed += instance.OnToggleFullScreen;
            @ToggleFullScreen.canceled += instance.OnToggleFullScreen;
            @SwitchLanguage.started += instance.OnSwitchLanguage;
            @SwitchLanguage.performed += instance.OnSwitchLanguage;
            @SwitchLanguage.canceled += instance.OnSwitchLanguage;
        }

        private void UnregisterCallbacks(IAlwaysActions instance)
        {
            @ToggleFullScreen.started -= instance.OnToggleFullScreen;
            @ToggleFullScreen.performed -= instance.OnToggleFullScreen;
            @ToggleFullScreen.canceled -= instance.OnToggleFullScreen;
            @SwitchLanguage.started -= instance.OnSwitchLanguage;
            @SwitchLanguage.performed -= instance.OnSwitchLanguage;
            @SwitchLanguage.canceled -= instance.OnSwitchLanguage;
        }

        public void RemoveCallbacks(IAlwaysActions instance)
        {
            if (m_Wrapper.m_AlwaysActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAlwaysActions instance)
        {
            foreach (var item in m_Wrapper.m_AlwaysActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AlwaysActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AlwaysActions @Always => new AlwaysActions(this);
    private int m_GamepadschemeSchemeIndex = -1;
    public InputControlScheme GamepadschemeScheme
    {
        get
        {
            if (m_GamepadschemeSchemeIndex == -1) m_GamepadschemeSchemeIndex = asset.FindControlSchemeIndex("Gamepad scheme");
            return asset.controlSchemes[m_GamepadschemeSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IGameActions
    {
        void OnStepForward(InputAction.CallbackContext context);
        void OnAuto(InputAction.CallbackContext context);
        void OnSave(InputAction.CallbackContext context);
        void OnLoad(InputAction.CallbackContext context);
        void OnQuickSave(InputAction.CallbackContext context);
        void OnQuickLoad(InputAction.CallbackContext context);
        void OnToggleDialogue(InputAction.CallbackContext context);
        void OnShowLog(InputAction.CallbackContext context);
        void OnShowConfig(InputAction.CallbackContext context);
        void OnReturnTitle(InputAction.CallbackContext context);
        void OnEditorReloadScripts(InputAction.CallbackContext context);
    }
    public interface IGameHoldActions
    {
        void OnQuitGame(InputAction.CallbackContext context);
    }
    public interface IGamePressActions
    {
        void OnFastForward(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnLeaveView(InputAction.CallbackContext context);
        void OnEditorUnlock(InputAction.CallbackContext context);
    }
    public interface IAlwaysActions
    {
        void OnToggleFullScreen(InputAction.CallbackContext context);
        void OnSwitchLanguage(InputAction.CallbackContext context);
    }
}
